services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: "sage-data-commons-dashboard:latest"
    pull_policy: never
    container_name: sage-data-commons-dashboard
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:10005 -Dcom.sun.management.jmxremote.port=64255 -Dcom.sun.management.jmxremote.rmi.port=64255 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
    volumes:
      - ${HOST_DASHBOARD_CONF_DIR}:/opt/app/conf:ro
      - ${HOST_DASHBOARD_DATA_DIR}:/opt/app/data:ro
    ports:
     - mode: host
       protocol: tcp
       published: 9090
       target: 8080
     - mode: host
       protocol: tcp
       published: 10005
       target: 10005
     - mode: host
       protocol: tcp
       published: 64255
       target: 64255
